### ISSUE TITLE
mustBeValidSize in openAIImages is unused

### ISSUE THREAD

**Issue by vpapanasta** [matlab-deep-learning/llms-with-matlab#29]
`mustBeValidSize` in `openAIImages` is unused. Shall we use it in the argument validation of nvpSize which we do in generate, edit and createVariation methods?

If we should use it and at the moment Size validation is wrong, then this is a bug. Otherwise, I would categorize it as an enhancement.

**Comment by ccreutzi** [comment]
The size validation did happen later. I'll remove the bug label.
