### ISSUE TITLE
Doc: decision support for how to include API-key

### ISSUE THREAD

**Issue by MiriamScharnke** [matlab-deep-learning/llms-with-matlab#64]
Should we point users to https://www.mathworks.com/help/matlab/import_export/keep-sensitive-information-out-of-code.html and how it's a good idea not to have API credentials in their code?

_Originally posted by @ccreutzi in https://github.com/matlab-deep-learning/llms-with-matlab/pull/63#discussion_r1695350611_

**Comment by ccreutzi** [comment]
Fixed in 57cf331
