### ISSUE TITLE
Streaming function errors

### ISSUE THREAD

**Issue by AngelVegaAlvarez** [matlab-deep-learning/llms-with-matlab#7]
Streaming function errors when a tool is called

**Comment by toshiakit** [comment]
Here is the script to reproduce the issue. 
```matlab
sf = @(x)fprintf("%s",x);
f = openAIFunction("generateImage","Geneates an image from a text prompt.");
f = addParameter(f,"Prompt",type="string", description="text prompt that describes the image to generate.");
chat = openAIChat("You are an AI assistant",StreamFun=sf, Tools=f);
 
prompts = ["Where is the capital of France?";"Create a 3D avatar of a whimsical sushi on the beach. "];
messages = openAIMessages;
for ii = 1:numel(prompts)
    prompt = prompts(ii)
    messages = addUserMessage(messages,prompt);
    [txt,message,response] = generate(chat,messages);
    if response.StatusCode ~= "OK"
        response.Body.Data.error
    end
end
```
This is the error when tool_calls were returned. 
<img width="426" alt="Screenshot 2024-02-13 141429" src="https://github.com/matlab-deep-learning/llms-with-matlab/assets/1530470/317316f6-e873-47e4-884f-b334e4b68c6a">

This is the intermittent error even when there is no tool_calls. 
<img width="437" alt="Screenshot 2024-02-13 150601" src="https://github.com/matlab-deep-learning/llms-with-matlab/assets/1530470/326122f4-2a0f-46a2-a279-a0534068cfaa">
