### ISSUE TITLE
OpenAIChat "generate" ignores chat ModelName

### ISSUE THREAD

**Issue by VenturiDTT** [matlab-deep-learning/llms-with-matlab#80]
Hello, thanks for the useful repository.
I found something that looks like a bug.
Given the following dummy example:

```
chat = openAIChat("You are a chatbot", 'APIKey', API_key, 'ModelName', 'gpt-3.5-turbo')
txt = generate(chat, "Hello")
```

I would expect this code to use gpt-3.5-turbo, instead the default "gpt-4.0-mini" is invoked. This is because of line 212 in "_openAIChat.m_":
```
          nvp.ModelName           (1,1) string {mustBeModel} = "gpt-4o-mini"
```

This seems wrong considered the example "_CreateSimpleChatBot.md_", where it is stated that "_This example uses the model gpt-3.5-turbo_", but the code is:

```
modelName = "gpt-3.5-turbo";
chat = openAIChat("You are a helpful assistant. You reply in a very concise way, keeping answers limited to short sentences.", ModelName=modelName);
[text, response] = generate(chat, messages);
```

To actually use "_gpt-3.5-turbo_" without changing "_openAIChat.m_", one should change the last line:

```
.modelName = "gpt-3.5-turbo";
chat = openAIChat("You are a helpful assistant. You reply in a very concise way, keeping answers limited to short sentences.", ModelName=modelName);
[text, response] = generate(chat, messages, ModelName=modelName);
```

Sorry if I misinterpreted something.

**Comment by ccreutzi** [comment]
Thanks, that was an oversight, showing a lack of a test seam for tests that would have caught the issue.
